In [1]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *


from pyspark.sql.functions import col,sum,avg,max

In [5]:
spark = SparkSession \
    .builder \
    .appName("test_nb") \
    .getOrCreate()

In [39]:
df_test = spark.read.format("parquet").load("../data/price_60day_info.parquet")
df_test.show(1)

+--------------------+------+----------+----------+----+--------------+--------+------------+----------+--------+------------+----------+------+------+----+--------------+--------+------------+--------+----------+----+--------------+--------+------------+--------+------------+----+--------+--------+------+------+------+------+------+------+--------+--------+--------+--------+--------+
|                 _id|  code|개인순매수|거래증가율|고가|고가기준등락율|고가대비|고가대비구분|기관순매수|    날짜|누적거래대금|누적거래량|등락율|소진율|시가|시가기준등락율|시가대비|시가대비구분|시가총액|외인순매수|저가|저가기준등락율|저가대비|저가대비구분|전일대비|전일대비구분|종가|종목코드|체결강도|회전율|  5map| 10map| 15map| 30map| 60map|    5mav|   10mav|   15mav|   30mav|   60mav|
+--------------------+------+----------+----------+----+--------------+--------+------------+----------+--------+------------+----------+------+------+----+--------------+--------+------------+--------+----------+----+--------------+--------+------------+--------+------------+----+--------+--------+------+------+------+------+------+------+--------+--------+--------+--------+--------+
|[5f76716aec932505...|010640|       478|    175.27|3035|          0.83|      25|           2|        -4|20200707|         781|    266747| -3.65|  4.41|3010|          0.00|       0|           3|   29000|      -474|2855|         -5.15|    -155|           5|     110|           5|2900|  010640|   43.39|  2.67|2900.0|2900.0|2900.0|2900.0|2900.0|266747.0|266747.0|266747.0|266747.0|266747.0|
+--------------------+------+----------+----------+----+--------------+--------+------------+----------+--------+------------+----------+------+------+----+--------------+--------+------------+--------+----------+----+--------------+--------+------------+--------+------------+----+--------+--------+------+------+------+------+------+------+--------+--------+--------+--------+--------+
only showing top 1 row

In [38]:
df_test.printSchema()

root
 |-- _id: struct (nullable = true)
 |    |-- oid: string (nullable = true)
 |-- code: string (nullable = true)
 |-- 개인순매수: string (nullable = true)
 |-- 거래증가율: string (nullable = true)
 |-- 고가: string (nullable = true)
 |-- 고가기준등락율: string (nullable = true)
 |-- 고가대비: string (nullable = true)
 |-- 고가대비구분: string (nullable = true)
 |-- 기관순매수: string (nullable = true)
 |-- 날짜: string (nullable = true)
 |-- 누적거래대금: string (nullable = true)
 |-- 누적거래량: string (nullable = true)
 |-- 등락율: string (nullable = true)
 |-- 소진율: string (nullable = true)
 |-- 시가: string (nullable = true)
 |-- 시가기준등락율: string (nullable = true)
 |-- 시가대비: string (nullable = true)
 |-- 시가대비구분: string (nullable = true)
 |-- 시가총액: string (nullable = true)
 |-- 외인순매수: string (nullable = true)
 |-- 저가: string (nullable = true)
 |-- 저가기준등락율: string (nullable = true)
 |-- 저가대비: string (nullable = true)
 |-- 저가대비구분: string (nullable = true)
 |-- 전일대비: string (nullable = true)
 |-- 전일대비구분: string (nullable = true)
 |-- 종가: string (nullable = true)
 |-- 종목코드: string (nullable = true)
 |-- 체결강도: string (nullable = true)
 |-- 회전율: string (nullable = true)
 |-- 5map: double (nullable = true)
 |-- 10map: double (nullable = true)
 |-- 15map: double (nullable = true)
 |-- 30map: double (nullable = true)
 |-- 60map: double (nullable = true)

In [42]:
#_test.printSchema()


df_test.select("code", "날짜", "종가", '누적거래량',  "5map", "10map", "15map", "30map", "60map", "5mav", "10mav", "15mav", "30mav", "60mav").where(col("code") == "005990").orderBy(desc("날짜")).show(10)

+------+--------+----+----------+-----------------+-----------------+--------+------------------+-----------------+------------------+------------------+----------+------------------+------------------+
|  code|    날짜|종가|누적거래량|             5map|            10map|   15map|             30map|            60map|              5mav|             10mav|     15mav|             30mav|             60mav|
+------+--------+----+----------+-----------------+-----------------+--------+------------------+-----------------+------------------+------------------+----------+------------------+------------------+
|005990|20200929|7950|      5676|7873.333333333333|7962.727272727273|7986.875| 7963.548387096775|8181.333333333333|            9987.5|12506.727272727272|   16768.0|17048.290322580644|15916.166666666666|
|005990|20200928|7940|      3844|7876.666666666667|7985.454545454545|7981.875| 7972.580645161291|8185.254237288135|11012.666666666666| 14403.90909090909| 17502.125|17261.129032258064|16089.728813559323|
|005990|20200925|7860|      7271|           7890.0|8001.818181818182|7975.625| 7981.935483870968|8189.482758620689|13252.333333333334| 18371.18181818182| 18703.625|           17592.0|16300.862068965518|
|005990|20200924|7710|     22684|7913.333333333333|8010.909090909091|7981.875| 7991.612903225807|8195.263157894737|           15675.5| 19221.18181818182|   20706.5| 17744.25806451613|16459.280701754386|
|005990|20200923|7890|      8139|7991.666666666667|8036.363636363636|  8002.5| 8007.096774193548| 8203.92857142857|14038.833333333334| 17972.81818181818|19851.6875| 17586.16129032258|         16348.125|
|005990|20200922|7890|     12311|           8040.0|           8040.0|  8007.5|8014.5161290322585|8209.636363636364|14993.333333333334|20061.272727272728|20062.9375|  17683.8064516129|16497.381818181817|
|005990|20200921|7970|     11827|8091.666666666667|8038.181818181818|  8017.5| 8020.645161290323|8215.555555555555|17365.666666666668|20525.909090909092|  21085.25| 17608.09677419355| 16574.90740740741|
|005990|20200918|8020|     17282|8116.666666666667|8026.363636363636|  8015.0|8024.5161290322585|8220.188679245282|           23308.5| 21547.81818181818|21436.0625|17606.677419354837|16664.490566037737|
|005990|20200917|8000|     21810|8106.666666666667|8020.909090909091| 8006.25| 8025.806451612903|8224.038461538461|23198.333333333332|           23551.0|20884.3125|17718.354838709678|16652.615384615383|
|005990|20200916|8180|     12864|           8105.0|8024.545454545455| 8006.25| 8026.774193548387| 8228.43137254902|21055.333333333332|22387.090909090908|20005.0625|17424.645161290322| 16551.49019607843|
+------+--------+----+----------+-----------------+-----------------+--------+------------------+-----------------+------------------+------------------+----------+------------------+------------------+
only showing top 10 rows

In [12]:
df_test.groupBy("code")

AttributeError: 'GroupedData' object has no attribute 'display'